### ISSUE TITLE
Please describe and/or add screenshots

### ISSUE THREAD

**Issue by probonopd** [CalebQ42/LinuxPA#1]
Hi, AppImage developer here, curious to learn more about your project. What does LinuxPA do that AppImages on their own cannot? Would be nice if you could make the description a little more verbose and could add some screenshots. Also, would be nice to discuss your ideas about portable apps and AppImage on http://discourse.appimage.org.

**Comment by CalebQ42** [comment]
The big problem I have with AppImages is that there is no easy way to organize and launch them (you could always just put them in folders to organize them, but that could get messy  and I, frankly, rather do a whole bunch of work to make my life a bit easier on a day to day basis. I definitely will add some screenshots and put some work into my README

**Comment by probonopd** [comment]
Why don't you just add them to the system's menu?

**Comment by CalebQ42** [comment]
Part of the reason is because I want it do as little host system modification as possible, but also so that it doesn't get confusing when the app is installed on the host system. Let's say that the host system is a public computer and has chromium installed, if you were to add the program to the system's menu it would be just plain confusing. The reason you wouldn't just use the app installed on the system is that the app on your flash drive is already configured to how you like it.

**Comment by CalebQ42** [comment]
Also a menu like mine is good for set-ups like mine. I have the PortableApps.com launcher and about 50 windows apps on my flash drive and (especially for games) I'd like my linux apps to be in the same directory as my windows games, but that can be really confusing and there's no super easy way to see if you have a linux version of a certain app (except for your memory).

**Comment by RoyiAvital** [comment]
This is lovely.

I really think this is the direction AppImage should pursuit.
Menu System like PortableApps (Or yours), with integration to the system yet with nothing installed system wide!
